athena/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls')),
    path('portfolio/',include('portfolio.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from portfolio.views import portfolio_view,portfolio_galview
app_name='portfolio'

urlpatterns=[
    path('details/<int:did>',portfolio_view,name='details'),
    path('<int:pid>',portfolio_galview,name='gallery'),
]

website/urls.py
from django.urls import path
from website.views import index_view,as_view

app_name='website'

urlpatterns=[
    path('',index_view,name='index'),
    path('as/',as_view,name='as'),
    # path('contact/',contact_view,name="contact"),
]

portfolio/models.py
from django.db import models

class All_col(models.Model):
    all_name=models.CharField(max_length=255)

    def __str__(self) :
        return self.all_name

class Pro_Gallery(models.Model):
    image = models.ImageField(upload_to='portfolio/', default='./portfolio-1.jpg')
    image_name=models.CharField(max_length=255,null=True, blank=True)
    
    def __str__(self) :
        return self.image_name
    class Meta:
        verbose_name_plural='pictures'

class Collection(models.Model):
    col_name=models.ForeignKey(All_col,on_delete=models.DO_NOTHING,null=True, blank=True)
    col_main_name=models.CharField(max_length=255,null=True, blank=True)
    col_desc = models.TextField()
    material=models.CharField(max_length=255)
    date=models.CharField(max_length=255)
    main_image=models.ImageField(upload_to='portfolio/', default='./portfolio-1.jpg')
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    # projects=models.ManyToManyField(Project)

    def __str__(self) :
        return self.col_main_name

class Project(models.Model):
    pro_name=models.CharField(max_length=255)
    description = models.TextField()
    size=models.CharField(max_length=300)
    main_image=models.ImageField(upload_to='portfolio/', default='./portfolio-1.jpg')
    gallery = models.ManyToManyField(Pro_Gallery)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    collection_name=models.ForeignKey(All_col,on_delete=models.DO_NOTHING,null=True, blank=True)

    def __str__(self) :
        return self.pro_name




# Create your models here.

website/models.py
from django.db import models

class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255,blank=True)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)  

    class Meta:
        ordering = ['created_date']
    def __str__(self):
        return self.name

class Artist_statement(models.Model):
    passage=models.TextField()

class CV(models.Model):
    cv_file=models.FileField(upload_to='website/')
# Create your models here.

website/forms.py
from django import forms
from website.models import Contact


class contactform(forms.ModelForm):

    #captcha = CaptchaField()

    class Meta :
        model=Contact
        fields= '__all__'

portfolio/views.py
from portfolio.models import Project,Collection
from django.shortcuts import redirect, render


def portfolio_galview(request,pid):

    projects=Project.objects.filter(collection_name_id=pid)
    collection=Collection.objects.get(col_name_id=pid)

    context={'projects':projects,'collection':collection }
    print(collection)
    return render(request,'portfolio/portfolio-gal.html',context)

def portfolio_view(request,did):

    #detail=Project.objects.filter(id=did)
    detail=Project.objects.get(id=did)
    
    nextpost = Project.objects.filter(created_date__gt=detail.created_date).order_by('created_date').first()
    prevpost = Project.objects.filter(created_date__lt=detail.created_date).order_by('created_date').last()


    context={'prevpost': prevpost , 'nextpost' : nextpost ,'detail':detail}
    return render(request,'portfolio/portfolio-single-3.html',context)
# Create your views here.

website/views.py
from django.shortcuts import render
from portfolio.models import Collection
from website.forms import contactform
from django.contrib import messages
from website.models import CV,Artist_statement

def index_view(request):

    collections=Collection.objects.all()
    cv=CV.objects.last()

    if request.method=='POST':
        form=contactform(request.POST)
        if form.is_valid():
            result=form
            result.save()
            messages.add_message(request,messages.SUCCESS,'your ticket submited successfully')
        else:
            messages.add_message(request,messages.ERROR,'your ticket did not submited')
    form=contactform()

    context={'collections':collections,'form':form,'cv':cv}
    return render(request,'website/index.html',context)

def as_view(request):

    statement=Artist_statement.objects.last()
    context={'statement':statement}

    return render(request,'website/as.html',context)

# def contact_view(request):
#     if request.method=='POST':
#         form=contactform(request.POST)
#         if form.is_valid():
#             name=form.cleaned_data['name']
#             result=form.save(commit=False)
#             result.name='unknown'
#             result.save()
#             messages.add_message(request,messages.SUCCESS,'your ticket submited successfully')
#         else:
#             messages.add_message(request,messages.ERROR,'your ticket did not submited')
#     form=contactform()

#     return render(request,"website/index.html",{'form':form})

# Create your views here.

templates/portfolio/portfolio-gal.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <title>Unfold &mdash; A onepage portfolio HTML template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta name="description" content="">
    <meta name="keywords" content="html, css, javascript, jquery">
    <meta name="author" content="">

    <link rel="stylesheet" href="{% static 'css/vendor/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/vendor/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/vendor/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/vendor/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/vendor/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/vendor/jquery.fancybox.min.css' %}">
    

    <!-- Theme Style -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body data-spy="scroll" data-target=".site-nav-target" data-offset="200">
    <nav class="unslate_co--site-mobile-menu">
        <div class="close-wrap d-flex">
          <a href="#" class="d-flex ml-auto js-menu-toggle">
            <span class="close-label">Close</span>
            <div class="close-times">
              <span class="bar1"></span>
              <span class="bar2"></span>
            </div>
          </a>
        </div>
        <div class="site-mobile-inner"></div>
    </nav>
    
      <div class="unslate_co--site-wrap">
    
        <div class="unslate_co--site-inner">
    
          <nav class="unslate_co--site-nav site-nav-target">
    
            <div class="container p-4">
    
              <div class="row align-items-center justify-content-between text-left">
                
                <div class="site-logo pos-absolute">
                  <a href="{% url 'website:index' %}" class="unslate_co--site-logo"><span><<<  </span>Home</a>
                </div>
                
              </div>
            </div>
    
          </nav>
          <!-- END nav -->
    
    <br><br><br><br><br><br>
    <div class="row justify-content-between align-items-stretch unslate_co--site-inner ">
        <div class="col-lg-8">
            <div class="container">
          
          
                <div class="relative"><div class="loader-portfolio-wrap"><div class="loader-portfolio"></div></div> </div>
                <div id="portfolio-single-holder"></div>
      
                <div class="portfolio-wrapper">
      
                  <div class="d-flex align-items-center mb-4 gsap-reveal gsap-reveal-filter">
                    <h2 class="mr-auto heading-h2"><span class="gsap-reveal">{{collection.col_name}}</span></h2>
      
                    <!-- <a href="#" class="text-white js-filter d-inline-block d-lg-none">Filter</a>
                    
                    <div class="filter-wrap">
                      <div class="filter ml-auto" id="filters">
                        <a href="#" class="active" data-filter="*">All</a>
                        <a href="#" data-filter=".web">Web</a>
                        <a href="#" data-filter=".branding">Branding</a>
                        <a href="#" data-filter=".illustration">Illustration</a>
                        <a href="#" data-filter=".packaging">Packaging</a>
                      </div>
                    </div> -->
                  </div>
  
                    <div id="posts" class="row gutter-isotope-item">
                      {% for project in projects %}
                        {% if forloop.counter|divisibleby:2 %}
                        <div class="item web branding col-sm-6 col-md-6 col-lg-4 isotope-mb-2">
                            <a href="{% url 'portfolio:details' did=project.id %}" class="portfolio-item  isotope-item gsap-reveal-img" data-id="1">
                            <div class="overlay">
                                
                                <div class="portfolio-item-content">
                                <h2 style="color: white;">{{project.pro_name}}</h2>
                                <h3>Number {{forloop.counter}}</h3>
                                </div>
                            </div>
                            <img src="{{project.main_image.url}}" class="lazyload  img-fluid" alt="Images" />
                            </a>
                        </div>
                        {% else %}
                        <div class="item branding packaging illustration col-sm-6 col-md-6 col-lg-4 isotope-mb-2 ">
                        <a href="{% url 'portfolio:details' did=project.id %}" class="portfolio-item  item-portrait isotope-item gsap-reveal-img" data-id="3">
                            <div class="overlay">
                                
                                <div class="portfolio-item-content">
                                <h2 style="color: white;">{{project.pro_name}}</h2>
                                <h3>Number {{forloop.counter}}</h3>
                                </div>
                            </div>
                            <img src="{{project.main_image.url}}" class="lazyload  img-fluid" alt="Images" />
                            </a>
                        </div>
                        {% endif %}
                      {% endfor %}
                    </div>
                    
                </div>
      
      
            </div>
        </div>
        <div class="col-lg-4 pl-lg-5 mt-5 p-3">
            <br><br><br>
            <div class="unslate_co--sticky">
              <div class="row">
                <div class="col-md-12 mb-4">
                  <div class="detail-v1">
                    <span class="detail-label">Collection Statement</span>
                    <p>{{collection.col_desc}}</p>
                  </div>
                </div>

                <div class="col-md-12 mb-4">
                  <div class="detail-v1">
                    <span class="detail-label">Material</span>
                    <span class="detail-val">{{collection.material}}</span>
                  </div>
                </div>

                <div class="col-md-12 mb-4">
                    <div class="detail-v1">
                      <span class="detail-label">Date</span>
                      <span class="detail-val">{{collection.date}}</span>
                    </div>
                </div>
              </div>
            </div> 
        </div>
    </div>
      
    <footer class="unslate_co--footer unslate_co--section" style="height:300px ;">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-md-7">
              
              <div class="footer-site-logo"><a href="#">Atena<span>.</span></a></div>

              <ul class="footer-site-social">
                <li><a href="#">Facebook</a></li>
                <li><a href="#">Twitter</a></li>
                <li><a href="#">Instagram</a></li>
                <li><a href="#">LinkedIn</a></li>
                <li><a href="#">Pinterest</a></li>
                
              </ul>

              <p class="site-copyright">
                
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                Copyright &copy;
                <script>
                  document.write(new Date().getFullYear());
                </script> All rights reserved | This template is made with <i class="icon-heart"
                  aria-hidden="true"></i> by <a href="#" target="_blank">Comphilia</a>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              
              </p>

            </div>
          </div>
        </div>
    </footer>
    <script src="{% static  'js/scripts-dist.js' %}"></script>
    <script src="{% static  'js/main.js' %}"></script>
    
</body>
</html>

templates/portfolio/portfolio-single-3.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <title>Unfold &mdash; A onepage portfolio HTML template by Colorlib</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  
  <meta name="description" content="">
  <meta name="keywords" content="html, css, javascript, jquery">
  <meta name="author" content="">

  <link rel="stylesheet" href="{% static 'css/vendor/icomoon/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/vendor/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/vendor/aos.css' %}">
  <link rel="stylesheet" href="{% static 'css/vendor/animate.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/vendor/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/vendor/jquery.fancybox.min.css' %}">

  <!-- Theme Style -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body data-spy="scroll" data-target=".site-nav-target" data-offset="200">

  <nav class="unslate_co--site-mobile-menu">
    <div class="close-wrap d-flex">
      <a href="#" class="d-flex ml-auto js-menu-toggle">
        <span class="close-label">Close</span>
        <div class="close-times">
          <span class="bar1"></span>
          <span class="bar2"></span>
        </div>
      </a>
    </div>
    <div class="site-mobile-inner"></div>
  </nav>

  <div class="unslate_co--site-wrap">

    <div class="unslate_co--site-inner">

      <nav class="unslate_co--site-nav site-nav-target">

        <div class="container p-4">

          <div class="row align-items-center justify-content-between text-left">
            
            <div class="site-logo pos-absolute">
              <a href="{% url 'website:index' %}" class="unslate_co--site-logo"><span><<<  </span>Home</a>
            </div>
            
          </div>
        </div>

      </nav>
      <!-- END nav -->

      <br><br><br><br>

      <div class="container">
        <div class="portfolio-single-wrap unslate_co--section" id="portfolio-single-section">
          <div class="portfolio-single-inner">

            <h3 class="heading-portfolio-single-h2">{{detail.pro_name}}</h3>

            <div class="row justify-content-between align-items-stretch">

              <div class="col-lg-8">
                  {% for image in detail.gallery.all %}
                  <p><a href="{{image.image.url}}" data-fancybox="gal"><img  src="{{image.image.url}}" alt="Image" class="img-fluid"></a></p>
                  {% endfor %}
                </div>
              <div class="col-lg-4 pl-lg-5">
                <div class="unslate_co--sticky">
                  <div class="row">
                    <div class="col-md-12 mb-4">
                      <div class="detail-v1">
                        <span class="detail-label">Project Statement</span>
                        <p>{{detail.description}}</p>
                      </div>
                    </div>

                    <div class="col-md-12 mb-4">
                      <div class="detail-v1">
                        <span class="detail-label">Size</span>
                        <span class="detail-val">{{detail.size}}</span>
                      </div>
                    </div>
                  </div>
                </div> 
              </div>

            </div>

          </div>
        </div>
        <div class="container-fluid">
          <div class="row">
              <div class="col-md-3 m-auto">
                <ul class="pagination">
                  {% if prevpost %}
                  <li class="page-item">
                    <a class="page-link" href="{% url 'portfolio:details' did=prevpost.id %}"><span><<<</span>Prev</a>
                  </li>
                  {% endif %}
                  {% if nextpost %}
                  <li class="page-item">
                    <a class="page-link" href="{% url 'portfolio:details' did=nextpost.id %}">Next<span>>>></span></a>
                  </li>
                  {% endif %}
                </ul>
              </div>
          </div>
            
        </div>
      </div>
    </div>
    

    <footer class="unslate_co--footer unslate_co--section">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-7">

            <div class="footer-site-logo"><a href="#">Atena<span>.</span></a></div>

            <ul class="footer-site-social">
              <li><a href="#">Facebook</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Instagram</a></li>
              <li><a href="#">LinkedIn</a></li>
              <li><a href="#">Pinterest</a></li>
            </ul>

            <p class="site-copyright">
                
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                Copyright &copy;
                <script>
                  document.write(new Date().getFullYear());
                </script> All rights reserved | This template is made with <i class="icon-heart"
                  aria-hidden="true"></i> by <a href="#" target="_blank">Comphilia</a>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              
              </p>

          </div>
        </div>
      </div>
    </footer>

  </div>

  <!-- Loader -->
  <div id="unslate_co--overlayer"></div>
  <div class="site-loader-wrap">
    <div class="site-loader"></div>
  </div>

  <script src="{% static 'js/scripts-dist.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>


</body>

</html>

templates/website/as.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <title>Unfold &mdash; A onepage portfolio HTML template by Colorlib</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  
  <meta name="description" content="">
  <meta name="keywords" content="html, css, javascript, jquery">
  <meta name="author" content="">

  <link rel="stylesheet" href="{% static 'css/vendor/icomoon/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/vendor/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/vendor/aos.css' %}">
  <link rel="stylesheet" href="{% static 'css/vendor/animate.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/vendor/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/vendor/jquery.fancybox.min.css' %}">

  <!-- Theme Style -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body data-spy="scroll" data-target=".site-nav-target" data-offset="200">

  <nav class="unslate_co--site-mobile-menu">
    <div class="close-wrap d-flex">
      <a href="#" class="d-flex ml-auto js-menu-toggle">
        <span class="close-label">Close</span>
        <div class="close-times">
          <span class="bar1"></span>
          <span class="bar2"></span>
        </div>
      </a>
    </div>
    <div class="site-mobile-inner"></div>
  </nav>

  <div class="unslate_co--site-wrap">

    <div class="unslate_co--site-inner">

      <nav class="unslate_co--site-nav site-nav-target">

        <div class="container p-4">

          <div class="row align-items-center justify-content-between text-left">
            
            <div class="site-logo pos-absolute">
              <a href="{% url 'website:index' %}" class="unslate_co--site-logo"><span><<<  </span>Home</a>
            </div>
            
          </div>
        </div>

      </nav>
      <!-- END nav -->

      <br><br><br><br><br>

      <div class="container">
        <h1 class="text-center">Artist Statement</h1>
        <br><br>
        <div class=" px-4 py-4" style="border: 2px solid #2c6eb9;"><h4 style="line-height: 33px;">{{statement.passage}}</h4></div>
      </div>
      <br><br><br>
        
    

     <footer class="mb-0">
      <div class="container">
        <div class="row ">
          <div class="col-md-7">

            <div class="footer-site-logo  "><h2><a href="{% url 'website:index' %}">Atena</a></h2></div><br><br>

            <ul class="footer-site-social ">
              <li><h4><a href="#">Facebook</a></h4></li>
              <li><h4><a href="#">Twitter</a></h4></li>
              <li><h4><a href="#">Instagram</a></h4></li>
              <li><a href="#">LinkedIn</a></li>
              <li><a href="#">Pinterest</a></li>
            </ul>
            <br><br>

            <p class="site-copyright ">
                
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                Copyright &copy;
                <script>
                  document.write(new Date().getFullYear());
                </script> All rights reserved | This template is made with <i class="icon-heart"
                  aria-hidden="true"></i> by <a href="#" target="_blank">Comphilia</a>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              
              </p>

          </div>
        </div>
      </div>
     </footer>

    </div>

  <!-- Loader -->
  <div id="unslate_co--overlayer"></div>
  <div class="site-loader-wrap">
    <div class="site-loader"></div>
  </div>

  <script src="{% static 'js/scripts-dist.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>


</body>

</html>